locations:
- name: Stage 1
  direction: vertical
  children:
  - name: LIGHTING-2 Rack
    nodes:
    - names: ["lighting-2"]
    - names: ["Pixie Driver 8k 2 Port 1"]
      ips: ["10.50.1.72"]
      macs: ["48:59:00:41:00:29"]
      avoid: true
    - names: ["Pixie Driver 8k 2 Port 2"]
      ips: ["10.50.1.73"]
      macs: ["48:59:00:28:00:27"]
      avoid: true
    - names: ["Pixie Driver 8k 2 Port 3"]
      ips: ["10.50.1.74"]
      macs: ["48:59:00:43:00:29"]
      avoid: true
    - names: ["Pixie Driver 8k 2 Port 4"]
      ips: ["10.50.1.75"]
      macs: ["48:59:00:42:00:29"]
      avoid: true
    - names: ["Pixie Driver 8k 2 Port 5"]
      ips: ["10.50.1.76"]
      macs: ["48:59:00:3c:00:3e"]
      avoid: true
    - names: ["Pixie Driver 8k 2 Port 6"]
      ips: ["10.50.1.77"]
      macs: ["48:59:00:3f:00:3e"]
      avoid: true
    - names: ["Pixie Driver 8k 2 Port 7"]
      ips: ["10.50.1.78"]
      macs: ["48:59:00:25:00:3e"]
      avoid: true
    - names: ["Pixie Driver 8k 2 Port 8"]
      ips: ["10.50.1.79"]
      macs: ["48:59:00:41:00:3e"]
      avoid: true
    - names: ["DMXG"] # cyc1
    - names: ["DMXH"] # cyc2
    - names: ["DMXI"] # cyc3
    - names: ["DMXJ"] # cyc4
    - names: ["DMXK"] # cyc5
    - names: ["DMXL"] # cyc6

  - direction: horizontal
    children:
    - nodes:
      - names: ["DMXQ"] # r2x1

    - nodes:
      - names: ["DMXR"] # r2x2

  - direction: horizontal
    children:
    - nodes:
      - names: ["MON1-A"]
      - names: ["MON1-B"]

- name: Under Apron
  direction: horizontal
  children:
  - name: AUDIO Rack
    nodes:
    - names: ["audio"]
    - names: ["MICS-A"]
      macs: ["00:0e:dd:a7:29:93"]
    - names: ["MICS-B"]
      macs: ["00:0e:dd:a8:3e:b3"]
    - names: ["MICS-C"]
      macs: ["00:0e:dd:a7:6f:55"]
    - names: ["MICS-D"]
      macs: ["00:0e:dd:64:3d:51"]
    - names: ["MICS-E"]
      macs: ["00:0e:dd:ac:fc:7d"]

  - name: LIGHTING-1 Rack
    nodes:
    - names: ["lighting-1"]
    - names: ["Pixie Driver 8k 1 Port 1"]
      ips: ["10.50.1.64"]
      macs: ["48:59:00:27:00:27"]
      avoid: true
    - names: ["Pixie Driver 8k 1 Port 2"]
      ips: ["10.50.1.65"]
      macs: ["48:59:00:37:00:27"]
      avoid: true
    - names: ["Pixie Driver 8k 1 Port 3"]
      ips: ["10.50.1.66"]
      macs: ["48:59:00:3e:00:27"]
      avoid: true
    - names: ["Pixie Driver 8k 1 Port 4"]
      ips: ["10.50.1.67"]
      macs: ["48:59:00:3f:00:27"]
      avoid: true
    - names: ["Pixie Driver 8k 1 Port 5"]
      ips: ["10.50.1.68"]
      macs: ["48:59:00:47:00:1a"]
      avoid: true
    - names: ["Pixie Driver 8k 1 Port 6"]
      ips: ["10.50.1.69"]
      macs: ["48:59:00:44:00:1a"]
      avoid: true
    - names: ["Pixie Driver 8k 1 Port 7"]
      ips: ["10.50.1.70"]
      macs: ["48:59:00:42:00:19"]
      avoid: true
    - names: ["Pixie Driver 8k 1 Port 8"]
      ips: ["10.50.1.71"]
      macs: ["48:59:00:44:00:19"]
      avoid: true

  - name: VIDEO Rack
    nodes:
    - names: ["video"]
    - names: ["ATEM 2 M/E Constellation 4K"]
    - names: ["HyperDeck-Studio-4K-Pro"]
    - names: ["RX-QLAB-1"]
    - names: ["RX-QLAB-2"]
    - names: ["TX-PROJ-1"]
    - names: ["TX-PROJ-2"]
    - names: ["TX-M4"]
    - names: ["TX-M16"]
    - names: ["TX-MISC"]
    - names: ["TX-PREVIEW"]

- direction: horizontal
  children:
  - nodes:
    - names: ["Y001-MAIN1-L-d1e155"]
      macs: ["ac:44:f2:4e:84:d6"]

  - name: Stage 2
    nodes:
    - names: ["MON2"]

  - name: Stage 3
    nodes:
    - names: ["MON3"]

  - nodes:
    - names: ["Y001-MAIN1-R-d1e194"]
      macs: ["ac:44:f2:4e:84:d4"]

- direction: horizontal
  children:
  - nodes:
    - names: ["RX-PROJ-1"]

  - nodes:
    - names: ["RX-PROJ-2"]

- direction: horizontal
  children:
  - nodes:
    - names: ["satellite-2"]
    - names: ["Y001-MAIN2-L-d1e298"]
      macs: ["ac:44:f2:4e:87:2a"]
    - names: ["DMXA"] # wash1
    - names: ["DMXB"] # wash2
    - names: ["DMXC"] # wash3
    - names: ["DMXM"] # focus{1,2}

  - nodes:
    - names: ["DMXN"] # focus{3,4}
    - names: ["DMXP"] # r3x{1,2}

  - nodes:
    - names: ["satellite-3"]
    - names: ["Y001-MAIN2-R-f0dd93"]
      macs: ["ac:44:f2:4e:87:27"]
    - names: ["DMXD"] # wash4
    - names: ["DMXE"] # wash5
    - names: ["DMXF"] # wash6
    - names: ["DMXO"] # focus{5,6}

- name: Booth
  direction: vertical
  children:
  - nodes:
    - names: ["satellite-1"]

  - direction: horizontal
    children:
    - name: Lighting Control
      nodes:
      - names: ["qlab"]
      - names: ["TX-QLAB-1"]
      - names: ["TX-QLAB-2"]
      - names: ["SK_PTZEXTREMEV2 [457081]"]
      - names: ["SK_RACKPRO2 [452514]"]
      - names: ["pigeon"]
      - names: ["showpi1"]
      - macs: ["d8:3a:dd:e3:5b:db"] # showpi2/artmap

    - name: Sound Control
      nodes:
      - names: ["SQ-7"]
        macs: ["00:04:c4:15:07:a4"]
      - names: ["BT"]

    - name: Camera Control
      nodes:
      - names: ["RX-CC-PREVIEW"]
      - names: ["RX-CC-M16"]
      - names: ["AtemPanel-7c2e0da86d22"]
      - names: ["AtemPanel-7c2e0da86d4c"]

    - name: Video Control
      nodes:
      - names: ["RX-VC-M4"]
      - names: ["RX-VC-M16"]
      - names: ["ATEM-2-ME-Advanced-Panel-20"]

    - name: Control
      nodes:
      - names: ["sunset"]
      - names: ["RX-CONTROL-1"]

shared_names:
  - "ULXD4Q G50 REV5"
