locations:
- name: Stage 1
  children:
  - children:
    - children:
      - name: LIGHTING-2 Rack
        nodes:
        - lighting-2
        - "48:59:00:41:00:29" # Pixie Driver 8k Port 1
        - "48:59:00:28:00:27" # Pixie Driver 8k Port 2
        - "48:59:00:43:00:29" # Pixie Driver 8k Port 3
        - "48:59:00:42:00:29" # Pixie Driver 8k Port 4
        - "48:59:00:3c:00:3e" # Pixie Driver 8k Port 5
        - "48:59:00:3f:00:3e" # Pixie Driver 8k Port 6
        - "48:59:00:25:00:3e" # Pixie Driver 8k Port 7
        - "48:59:00:41:00:3e" # Pixie Driver 8k Port 8
        - ART9 # Cyc
        - ART10 # Cyc
        - ART11 # Cyc
        - ART12 # Cyc
        - ART13 # Cyc
        - ART14 # Cyc

    - children:
      - children:
        - nodes:
          - ART16 # R2X1

        - nodes:
          - ART20 # R2X2

    - children:
      - nodes:
        - "MON1-A"
        - "MON1-B"

- name: Under Apron
  children:
  - name: AUDIO Rack
    nodes:
    - audio
    - "MICS-A"
    - "00:0e:dd:a7:29:93" # MICS-A bridge interface
    - "MICS-B"
    - "00:0e:dd:a8:3e:b3" # MICS-B bridge interface
    - "MICS-C"
    - "00:0e:dd:a7:6f:55" # MICS-C bridge interface
    - "MICS-D"
    - "00:0e:dd:64:3d:51" # MICS-D bridge interface
    - "MICS-E"
    - "00:0e:dd:ac:fc:7d" # MICS-E bridge interface

  - name: LIGHTING-1 Rack
    nodes:
    - lighting-1
    - "48:59:00:27:00:27" # Pixie Driver 8k Port 1
    - "48:59:00:37:00:27" # Pixie Driver 8k Port 2
    - "48:59:00:3e:00:27" # Pixie Driver 8k Port 3
    - "48:59:00:3f:00:27" # Pixie Driver 8k Port 4
    - "48:59:00:47:00:1a" # Pixie Driver 8k Port 5
    - "48:59:00:44:00:1a" # Pixie Driver 8k Port 6
    - "48:59:00:42:00:19" # Pixie Driver 8k Port 7
    - "48:59:00:44:00:19" # Pixie Driver 8k Port 8

  - name: VIDEO Rack
    nodes:
    - video
    - "ATEM 2 M/E Constellation 4K"
    - "HyperDeck-Studio-4K-Pro"
    - RX-QLAB-1
    - RX-QLAB-2
    - TX-PROJ-1
    - TX-PROJ-2
    - TX-M4
    - TX-M16
    - TX-MISC
    - TX-PREVIEW

- children:
  - nodes:
    - "Y001-MAIN1-L-d1e155"
    - "ac:44:f2:4e:84:d6" # MAIN1-L bridge interface

  - name: Stage 2
    nodes:
    - "MON2"

  - name: Stage 3
    nodes:
    - "MON3"

  - nodes:
    - "Y001-MAIN1-R-d1e194"
    - "ac:44:f2:4e:84:d4" # MAIN1-R bridge interface

- children:
  - nodes:
    - "RX-PROJ-1"

  - nodes:
    - "RX-PROJ-2"

- children:
  - nodes:
    - satellite-2
    - "Y001-MAIN2-L-d1e298"
    - "ac:44:f2:4e:87:2a" # MAIN2-L bridge interface
    - ART3 # Wash
    - ART4 # Wash
    - ART5 # Wash
    - ART17 # Focus

  - nodes:
    - ART15 # R3X
    - ART18 # Focus

  - nodes:
    - satellite-3
    - "Y001-MAIN2-R-f0dd93"
    - "ac:44:f2:4e:87:27" # MAIN2-R bridge interface
    - ART6 # Wash
    - ART7 # Wash
    - ART8 # Wash
    - ART19 # Focus

- name: Booth
  children:
  - children:
    - name: SATELLITE-1 Rack
      nodes:
      - satellite-1

    - children:
      - name: Lighting Control
        nodes:
        - qlab
        - TX-QLAB-1
        - TX-QLAB-2
        - "SK_PTZEXTREMEV2 [457081]"
        - "SK_RACKPRO2 [452514]"
        - pigeon
        - showpi1
        - showpi2
  
      - name: Sound Control
        nodes:
        - SQ-7
        - "00:04:c4:15:07:a4" # SQ-7 bridge port
        - BT
  
      - name: Camera Control
        nodes:
        - RX-CC-PREVIEW
        - RX-CC-M16
        - "AtemPanel-7c2e0da86d22"
        - "AtemPanel-7c2e0da86d4c"
  
      - name: Video Control
        nodes:
        - RX-VC-M4
        - RX-VC-M16
        - "ATEM-2-ME-Advanced-Panel-20"
  
      - name: Control
        nodes:
        - sunset
        - RX-CONTROL-1
